# specify the version of docker-compose
version: "3.8"

# define the services/containers to be run
services:
  # define the worker service
  worker:
    depends_on: 
      - redis
      - db
    build: ./worker
    ports:
      - 3001:3001
    environment:
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgres://postgres:postgres@db:5432/cymail
    develop:
      # we specify the files to watch for changes
      watch:
        # it'll watch for changes in package.json and package-lock.json and rebuild the container if there are any changes
        - path: ./worker/package.json
          action: rebuild
        - path: ./worker/package-lock.json
          action: rebuild
        # it'll watch for changes in the worker directory and sync the changes with the container real time
        - path: ./worker
          target: /app
          action: sync

  # define the api service/container
  core: 
    # api service depends on the db service so the db service will be started before the api service
    depends_on: 
      - db
      - redis
    build: ./core
    ports: 
      - 3000:3000
    environment: 
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgres://postgres:postgres@db:5432/cymail
      WORKER_URL: http://worker:3001
    develop:
      # specify the files to watch for changes
      watch:
        # it'll watch for changes in package.json and package-lock.json and rebuild the container and image if there are any changes
        - path: ./core/package.json
          action: rebuild
        - path: ./core/package-lock.json
          action: rebuild
        
        # it'll watch for changes in the core directory and sync the changes with the container real time
        - path: ./core
          target: /app
          action: sync

  # define the db service
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    user: postgres
    environment:
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=postgres
    volumes:
      - cymail:/data/db

  # define the redis service
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - cymail:/data/db

# define the volumes to be used by the services
volumes:
  cymail: