version: '3'

services:
  core:
    build:
      context: ./core
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./core:/usr/src/app
    tty: true
    restart: always
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=phishy_db
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - phishy-network

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - phishy-network

networks:
  phishy-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
