name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-project:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js 20.x
      uses: actions/setup-node@master
      with:
        node-version: '20.x'
    - name: Build the Core Service Docker image
      run: docker build ./core --file ./core/Dockerfile --tag core-api:$(date +%s)

  push-to-dockerhub:
    needs: build-project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        file: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}:latest
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
