name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js 20.x
      uses: actions/setup-node@master
      with:
        node-version: '20.x'
    - name: Build the Core Service Docker image
      run: docker build ./core --file ./core/Dockerfile --tag core-api:$(date +%s)
